### ISSUE TITLE
No mail in `Trash` folders when removed a mail

### ISSUE THREAD

**Issue by mzch** [stalwartlabs/imap-server#6]
When removed a mail, no mail moves to `Trash`, `Deleted Messages` or `Deleted Items`. It's lost.

OS: macOS `13.1`
App: Apple Mail.app `16.0`, Airmail `5.5.82`, GyazMail `1.7.1`

**Comment by MHuesler** [comment]
I believe, that this is the intended behavior. When an email is flagged as deleted and expurged, it should be removed from the folder and not moved to a trash folder.

This is probably an issue with the email clients that move the email messages to the trash folder. I believe #5 and #10 are related to this. If the clients use the folder UID validity to identify folders, they won't find them because stalwart-imap returns the same validity for all folders.
